apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-sync
  namespace: flux-system
spec:
  interval: 1h
  path: "./apps"
  prune: true
  dependsOn:
    - name: envoy-gateway-resources # Wait for the gateway to be ready
  sourceRef:
    kind: GitRepository
    name: flux-system