apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy
spec:
  interval: 1h
  targetNamespace: envoy-gateway-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: envoy-gateway
      version: "v1.2.x" # Use the Envoy Gateway chart, not raw Envoy
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway # Points to the OCI repo above
      interval: 1h
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway
  namespace: envoy
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All # Allows podinfo in 'default' to connect