apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: envoy
spec:
  interval: 1h
  releaseName: envoy-gateway
  targetNamespace: envoy # Recommended namespace
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: envoy-gateway
      version: "v1.2.x" # Pin to a minor version for stability
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: envoy
      interval: 1h
  values:
    # Minimal config: The defaults are usually sufficient for EKS
    config:
      envoyGateway:
        gateway:
          controllerName: gateway.envoyproxy.io/gatewayclass-controller