# envoy-gateway needs a custom install method because of
# the CRDs. This Kustomization file separately installs
# envoy-gateway and the certs that it provisions
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-controller
  namespace: flux-system
spec:
  interval: 15m
  path: ./apps/envoy-gateway/overlays/dev
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars
---
# This Kustomization creates just the custom resources
# which relies on the CRDs, hence the dependsOn
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: envoy-gateway-controller
  interval: 15m
  path: ./infrastructure/gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-vars