apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-installer
  namespace: flux-system
spec:
  interval: 1h
  path: "./infrastructure/envoy-gateway"
  # We exclude the subfolder so this sync ONLY sees the HelmRelease
  commonMetadata:
    labels:
      app.kubernetes.io/part-of: envoy-gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-config
  namespace: flux-system
spec:
  dependsOn:
    - name: envoy-gateway-installer # <--- THE MAGIC LINE
  interval: 1h
  path: "./infrastructure/envoy-gateway/config"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system