apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-sync
  namespace: flux-system
spec:
  interval: 1h
  path: "./infrastructure" # Points to your global infra folder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system