# Does nothing but instruct flux to acknowledge of a new git repo to monitor for changes
# but says nothing about what to do when a ne change is detected.
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
