apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: flux-system
spec:
  interval: 1h
  releaseName: envoy-gateway
  targetNamespace: envoy-gateway-system
  install:
    createNamespace: true
    crds: CreateReplace
  chart:
    spec:
      chart: envoy-gateway
      version: "v1.2.x"
      sourceRef:
        kind: HelmRepository
        name: envoy-gateway
        namespace: flux-system